version: "3.9"

services:
  redis:
    image: redis:7
    container_name: order-redis
    ports:
      - "6379:6379"
    volumes:
      - "redis_data:/data"
  postgres:
    image: postgres:16
    container_name: order-postgres
    environment:
      POSTGRES_USER: orderuser
      POSTGRES_PASSWORD: orderpass
      POSTGRES_DB: ordersdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  redis_data:
