apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-server

spec:
  replicas: 3
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: publisher

spec:
  replicas: 2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory

spec:
  replicas: 2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification

spec:
  replicas: 2