package grpctransport

import (
	"context"

	// Generated from grpc/order.proto
	// Contains:
	// - protobuf message types
	// - gRPC client interfaces
	// - gRPC server interfaces
	orderspb "order-system/grpc"

	// Our domain model
	"order-system/internal/domain"

	// Business logic layer
	"order-system/internal/service"
)

//////////////////////////////////////////////////////////////////
// OrderGRPCServer
//////////////////////////////////////////////////////////////////

// This struct is our gRPC adapter.
//
// Think:
//
// Network Request
//        |
//        v
// OrderGRPCServer
//        |
//        v
// OrderService
//        |
//        v
// PostgreSQL
//
// This layer should contain:
//
// ✓ request/response mapping
// ✓ gRPC concerns
//
// This layer should NOT contain:
//
// ✗ SQL
// ✗ business rules
// ✗ repository logic
//
type OrderGRPCServer struct {

	// Generated by protoc.
	//
	// Embedding this ensures that if we later add new RPCs
	// to the proto file, our code remains forward compatible.
	//
	// Without it, future proto changes can break compilation.
	//
	orderspb.UnimplementedOrderServiceServer

	// Real business logic.
	//
	// The gRPC layer should delegate work to the service.
	//
	service *service.OrderService
}

//////////////////////////////////////////////////////////////////
// Constructor
//////////////////////////////////////////////////////////////////

func NewOrderGRPCServer(service *service.OrderService) *OrderGRPCServer {
	return &OrderGRPCServer{
		service: service,
	}
}

//////////////////////////////////////////////////////////////////
// Mapping Helpers
//////////////////////////////////////////////////////////////////

// Converts:
//
// protobuf Order
//
// into
//
// domain Order
//
// Why?
//
// We do NOT want our service layer
// depending on protobuf-generated types.
//
func toDomainOrder(o *orderspb.Order,) domain.Order {

	if o == nil {
		return domain.Order{}
	}

	return domain.Order{
		ID:         o.Id,
		CustomerID: o.CustomerId,
		ProductID:  o.ProductId,
		Quantity:   int(o.Quantity),
		Amount:     o.Amount,
	}
}

// Converts:
//
// domain Order
//
// into
//
// protobuf Order
//
// Used when returning responses.
//
func toProtoOrder(o domain.Order,) *orderspb.Order {

	return &orderspb.Order{
		Id:         o.ID,
		CustomerId: o.CustomerID,
		ProductId:  o.ProductID,
		Quantity:   int32(o.Quantity),
		Amount:     o.Amount,
	}
}

//////////////////////////////////////////////////////////////////
// CreateOrder RPC
//////////////////////////////////////////////////////////////////

// Generated interface:
//
// CreateOrder(
//     context.Context,
//     *CreateOrderRequest,
// )
//
// Context comes from the gRPC runtime.
//
// The same ctx can flow:
//
// Client
//   |
//   v
// gRPC
//   |
//   v
// Service
//   |
//   v
// Repository
//   |
//   v
// PostgreSQL
//
// Deadlines and cancellations automatically propagate.
//
func (s *OrderGRPCServer) CreateOrder(
	ctx context.Context,
	req *orderspb.CreateOrderRequest,
) (*orderspb.CreateOrderResponse, error) {

	//////////////////////////////////////////////////////////
	// Transport -> Domain
	//////////////////////////////////////////////////////////

	order := toDomainOrder(
		req.GetOrder(),
	)

	//////////////////////////////////////////////////////////
	// Business Logic
	//////////////////////////////////////////////////////////

	savedOrder, err := s.service.CreateOrder(
		ctx,
		order,
	)

	if err != nil {
		return nil, err
	}

	//////////////////////////////////////////////////////////
	// Domain -> Transport
	//////////////////////////////////////////////////////////

	return &orderspb.CreateOrderResponse{
		Order: toProtoOrder(savedOrder),
	}, nil
}

//////////////////////////////////////////////////////////////////
// ListOrders RPC
//////////////////////////////////////////////////////////////////

func (s *OrderGRPCServer) ListOrders(
	ctx context.Context,
	req *orderspb.ListOrdersRequest,
) (*orderspb.ListOrdersResponse, error) {

	//////////////////////////////////////////////////////////
	// Business Logic
	//////////////////////////////////////////////////////////

	orders,err := s.service.ListOrders(
		ctx,
	)

	if err != nil {
		return nil, err
	}

	//////////////////////////////////////////////////////////
	// Domain -> Transport
	//////////////////////////////////////////////////////////

	resp := &orderspb.ListOrdersResponse{
		Orders: make(
			[]*orderspb.Order,
			0,
			len(orders),
		),
	}

	for _, order := range orders {

		resp.Orders = append(
			resp.Orders,
			toProtoOrder(order),
		)
	}

	return resp, nil
}