apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory
  template:
    metadata:
      labels:
        app: inventory
    spec:
      containers:
        - name: inventory
          image: order-system-inventory:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: DB_NAME
              value: inventorydb
          envFrom:
            - configMapRef:
                name: order-config
            - secretRef:
                name: order-secret