apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - order-config.yaml
  - order-secret.yaml
  - redis-deployment.yaml
  - order-server.yaml
  - publisher.yaml
  - inventory.yaml
  - notification.yaml

  - postgres/postgres-config.yaml
  - postgres/postgres-secret.yaml
  - postgres/postgres-pvc.yaml
  - postgres/postgres-deployment.yaml