apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor

metadata:
  name: order-server

spec:
  selector:
    matchLabels:
      app: order-server

  endpoints:
    - port: metrics
      path: /metrics
      interval: 15s